### ISSUE TITLE
Use more intelligible icons for grid layout and desktop layout

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#105]
The icons should look more like the ones in the mockups. Also, add hover-over text saying 'grid layout' and 'desktop layout'.

**Comment by hoganmaps** [comment]
No longer relevant - Grid/Desktop layout is now part of the dashboard edit modal and no longer a toggle in the app toolbar

**Comment by tonyalletag** [comment]
closed based on last comment
