### ISSUE TITLE
Upgrade to Angular 1.4

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#227]
AngularJS v 1.3 was released on 10/13. We will need to ensure all of our angular dependencies support 1.3 before upgrading, including:

* angular-bootstrap
* angular-gridster
* angular-ui-router

**Comment by mparizernc** [comment]
I smoked tested the webtop with all of the browsers in develop.  I found a couple issues that are documented in other tickets. I can't say if they were because of the upgrade or preexisting issues.

**Comment by mparizernc** [comment]
In staging I smoke tested the webtop in all of the browsers to verify new bugs were found.
