### ISSUE TITLE
Allow more apps to be added when maximum number of grid rows reached

### ISSUE THREAD

**Issue by rweintr** [ozone-development/ozp-webtop#309]
When maximum number of rows are reached in grid, allow a new app to be added to dashboard in new column.

**Comment by hoganmaps** [comment]
inadvertently fixed when the columns were removed when loading apps. There is no row limit, just an app limit.

**Comment by mparizernc** [comment]
I was able to add the max 15 widgets and put them all in separate rows and extend the rows sizes by increasing the length of the widgets in develop.

**Comment by mparizernc** [comment]
Staging worked as expected.
