### ISSUE TITLE
Blank frames appear and require multiple refreshes to restore content

### ISSUE THREAD

**Issue by rweintr** [ozone-development/ozp-webtop#344]
At random times, all the application tiles in all dashboards in both grid and desktop layout lose their content and appear as blank frames. In order to correct this issue, multiple webtop reloads performed by closing an opening web browser are required. This behavior has been seen in Google Chrome (not seen in FF or IE yet).

**Comment by sdeighan** [comment]
@arw180 @hoganmaps @SOAP1914  - Is this still an issue?

**Comment by hoganmaps** [comment]
@sdeighan I don't think it is still an issue. I just talked with @clarkjefcoat and no users have reported problems with blank frames/widgets except when they un-bookmark a widget, which was addressed by issue #411

**Comment by sdeighan** [comment]
Closing issue as OBE
