### ISSUE TITLE
iframe size is too small in layout view

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#390]
Look at the FrameIt app to see the problem - iframe container size is too small - the bottom toolbar on FrameIt is almost entirely cut off. Resizing the widget further demonstrates the problem.

**Comment by arw180** [comment]
It's possible this is a problem with FrameIt and not the iframe size - need to investigate

**Comment by arw180** [comment]
Jason has reported the same issue, so this is almost certainly a webtop bug. the problem exists in grid layout as well as desktop layout, though the problem is worse in desktop mode.

**Comment by mparizernc** [comment]
FF, IE11, Chrome (unable to test in IE9)

Verified that the toolbar for the FrameIt widget is no longer cut off.  Ready for testing in Prod.
