### ISSUE TITLE
Load system notifications from backend

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#397]
Replace the hard-coded example notifications with real ones from the backend

**Comment by arw180** [comment]
Do we have a mockup for how this should look? System notifications won't have images (or if they do they will all be the same, I imagine), unlike the sample app-notifications currently in place in webtop. Will both system and app notifications show up here, each under their own heading?

**Comment by wski** [comment]
Tested, it works

**Comment by kgordon-1** [comment]
Passed - tested in STG
Verified fixed by creating message to display in alert for a day.
