### ISSUE TITLE
Launching from HUD to Webtop in IE9 causes an existing widget to be replaced

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-webtop#401]
Steps:
1) Launch a listing from HUD into Webtop
2) Go back to HUD
3) Launch a different listing into Webtop

Result: The second listing appears in the Webtop but the first is no longer in Webtop
Expected Result: Both listings should appear in Webtop

I tried this in Chrome, FF and IE11 and it works correctly in those browsers.

**Comment by tonyalletag** [comment]
IE is no longer a supported browser
