### ISSUE TITLE
Deleting a dashboard causes an unnecessary dashboard change

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#419]
If you have 3 dashboards and are currently viewing dashboard #2 and then delete dashboard #3, your current dashboard will be changed to dashboard #1 (the first board). This is confusing and unnecessary - the user should only be redirected to their first dashboard if they delete their currently active dashboard.

**Comment by wski** [comment]
Tested on CI- this doesn't happen for me anymore, resolved

**Comment by kgordon-1** [comment]
Verified fixed 2 ways  
•	Not in dashboard but in another dashboard.  Click on dashboard name to display menu and deleted a dashboard.  System stayed in current dashboard.
•	In current dashboard and delete it.  Dashboard went blank, all apps were deleted.  Refresh, blank dashboard displayed.  
•	Both cases, the selected dashboard was deleted
