### ISSUE TITLE
Newly added widgets are hard to find in grid layout

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#420]
If you have numerous widgets in grid layout and you add a new widget to the dashboard, it will often be displayed below the fold (i.e. require scrolling to see), but since the webtop doesn't automatically scroll to the location of the newly-added widget, it's not apparent to the user that their action of adding a new widget to their dashboard actually did anything.

Suggestion: automatically scroll to the location of newly added widgets

**Comment by bhalt** [comment]
Is it possible to introduce a smarter method of displaying new apps on the grid view? Calculate the current window width and then display newly added apps left-to-right, top-to-bottom...?

**Comment by bhalt** [comment]
Also, can we add a gentle highlight to the new app (on both grid and desktop views): 

CSS on li.gridster-item for 1.5-2 seconds:


  box-shadow: 0 0 15px #009dd3;






![uploads/e9435110-bf06-4316-bd98-ebaa5471b290/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe9435110-bf06-4316-bd98-ebaa5471b290%2Fblob)

**Comment by bhalt** [comment]
@hoganmaps also this ^

**Comment by mparizernc** [comment]
I have tested this on develop with all the browsers and verified opening widgets with new dashboards, existing dashboards and opening from the HUD.

The border work will be done in #596.

**Comment by mparizernc** [comment]
Verified in Staging that widgets are added to the first row and then subsequent rows when the existing row is filled with widgets.
