### ISSUE TITLE
Newly added widgets occasionally hide in grid layout

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#422]
Sometimes a widget is added to the current dashboard and although its icon shows up in the task bar at the bottom, the frame itself is not displayed in the grid layout. Clicking on the icon in the task bar will cause the widget to show up and get highlighted, but that highlighting fails to fade automatically (seen in FF)

**Comment by hoganmaps** [comment]
unable to reproduce now, will re-open if we experience this issue again

**Comment by mparizernc** [comment]
I have not seen this issue either. I confirmed with Alan that this is OK to close.
