### ISSUE TITLE
Lots of dead links in the top toolbar

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#423]
These links should be updated to point to valid center and hud locations (or internal modals) as appropriate. See the HUD for some examples.

**Comment by arw180** [comment]
Need to confirm this behavior:

Help icon -> open help link in modal window (Ozone Help Zone)
Bookmarks -> open HUD in current window
Profile -> open profile info in modal. Name, username, email. User's Listings (list of Marketplace listings owned by this user)
Settings -> Settings in modal. Unclear what these might be for webtop right now
Submit a Listing -> Submit a listing page in Center (open in current window)
Developer Resources -> TBD?
Listing Management -> Center my-listings page in current window

**Comment by arw180** [comment]
Also need to confirm with Bethany that we have the latest ozp toolbar - if HUD and Center are any indication, I think the answer is no.

**Comment by tonyalletag** [comment]
This needs to be fixed for IOB 
Settings -> is fine how it functions now - Text in modal should be "Webtop Currently has no configurable user settings"
Developer Resources -> Should point to ADV - this link needs to be in a config file

**Comment by mparizernc** [comment]
Help and Profile modals will be completed as part of the work done in tickets #534 and #531

**Comment by mparizernc** [comment]
All Browsers

I have verified all of the links in the User Drop down go to the correct locations. This is ready to be tested in Prod.

**Comment by jloveland18** [comment]
tested in staging 0.7.6

All Browsers

I've verified all User Drop down links open the correct locations.
