### ISSUE TITLE
PUT on <iwc url>/undefined/dashboard-data 405 (Not Allowed)

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#429]
Where is this error coming from? I see it whenever loading webtop - locally it looks like "PUT http://localhost:8003/undefined/dashboard-data 405 (Not Allowed)"

**Comment by arw180** [comment]
Apparently this prevents dashboards from being saved...

**Comment by Kevin-K** [comment]
ozp-iwc issue.

Fixed in [v0.1.5](https://github.com/ozone-development/ozp-iwc/tree/v0.1.5)
