### ISSUE TITLE
Switch from ubuntu-light to ubuntu-regular fonts

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-webtop#431]

**Comment by sdeighan** [comment]
Ubuntu Light was mandated by the style guide; any further background on this ticket?

**Comment by hoganmaps** [comment]
I _think_ it this was related to some style overrides we were doing in webtop, but I don't remember exactly.

**Comment by rpokorny** [comment]
IIRC Center and HUD use regular Ubuntu with a font-weight of 300 (normal being 400).  webtop on the other hand was using the actual Ubuntu-Light font.  I don't remember for sure if this ticket was just a consistency matter or there were actual problems that people were seeing, but I feel like there might've been some inconsistencies between the products resulting from this.

**Comment by arw180** [comment]
@rpokorny is correct - this issue was created to track the fact that Webtop was using the Ubuntu-Light font in place of the Ubuntu-Regular font. This has since been undone, and I recommend closing this issue and creating a new, more specific one if a specific problem with font weight exists.
