### ISSUE TITLE
Widget resize is flaky at best in both Grid and Desktop layouts (IE9)

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#439]

**Comment by clarkjefcoat** [comment]
Originally had this as IOB, but marked as Post-IOB in current schedule.

**Comment by hoganmaps** [comment]
ie9 issues being moved out of IOB and in to backlog. need to evaluate later

**Comment by tonyalletag** [comment]
The OZP development team does not code or test to IE9.  Our current browser baseline is IE11, FF24+, Chrome 36+
