### ISSUE TITLE
Use the correct icons and add hover effects

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#465]
Evaluate all icons in use in webtop and make sure they're the correct ones (size, color, etc). Also add the hover over effects

**Comment by arw180** [comment]
@sdeighan I think this ticket has outlived its usefulness - are there any outstanding icon/hover issues you're aware of in webtop (things that worked before the big icon transition but don't work now)?

**Comment by sdeighan** [comment]
Not that I know of
