### ISSUE TITLE
Listing Intermittently doesn't save

### ISSUE THREAD

**Issue by jloveland18** [ozone-development/ozp-webtop#485]
Steps to Recreate:
1. Click on the three Horizontal lines in the top right corner.
2. Select submit listing.
3. Fill in name and listing type.
4. Select save.
5. Click on the three Horizontal lines in the top right corner.
6. Select listing Management.
7. Find the box with today's date.
8. Select the drop down arrow on the top right corner of the box and select edit.
9. Completely fill out the form (under Graphics -> Screenshots make sure you select 'add' and add two Screenshots- this is Mandatory or else you can't save Successfully).
10. Select save.

Current Behavior: Sometimes the listing saves the first time and Sometimes you have to keep trying Several times before the listing finally saves.
Expected Behavior: The listing should save on the first try.

**Comment by clarkjefcoat** [comment]
This issue was moved to ozone-development/ozp-center#196
