### ISSUE TITLE
Hide metrics link unless user is an app mall steward or content steward

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#490]

**Comment by arw180** [comment]
The page must also be hidden if users manually navigate to it (and are not content/apps mall stewards).

To get this information, use the `marketplace/api/profile/self` endpoint and look at the `highestRole` field that is returned. Add this API call to `restInterface.js` and call it `getProfile()`. It should return at least highestRole, email, id, displayName, and userName

**Comment by arw180** [comment]
Also, this should open up in a new tab

**Comment by clarkjefcoat** [comment]
We will be using a new role called METRICS to indicate a user has access to metrics.  A user with the ADMIN or METRICS role should be allowed to view metrics.

**Comment by wski** [comment]
Tested with test user and test admin, resolved

**Comment by kgordon-1** [comment]
Passed - Tested in STG
Verified fixed by entering AppsMall as a general user and clicking on the triple lines in all 3 web pages (HUD,WT and Center).  Metrics link is no longer displayed as an option.
