### ISSUE TITLE
Disabled apps still accessible on webtop

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-webtop#502]
When an app is published but disabled the app is still accessible on webtop.  Is this as designed?

**Comment by TheAndyStumpf** [comment]
See question 76 from ozp-hud (https://github.com/ozone-development/ozp-hud/issues/76).

**Comment by hoganmaps** [comment]
When an app has been un-bookmarked, the app is no longer accesible/the user is given a message in the old app frame that it was probably un-bookmarked.

**Comment by jal-vsi** [comment]
Passed test in Develop (IE9/11, CH, FF).

**Comment by jal-vsi** [comment]
Passed test in Master (IE9/11, CH, FF).  Open app in Webtop, unbookmark it in either HUD or Center, go to Webtop and note the message indicating it was probably unbookmarked and is not active, go to Center and rebookmark it, confirm in Webtop it is active again.

**Comment by tonyalletag** [comment]
@hoganmaps @jal-vsi I believe this ticket was referring to a Center Admin disabling an App and then not making that App visible on the users HUD and Webtop.

**Comment by tdressel** [comment]
Passed on Staging using Chrome 36, FF31 and IE10.

Steps Used to test-
Test 1-
Visibility enabled and Bookmarked
RESULTS - Visible in HUD, Searchable in Center, Visible in Webtop

Test 2- 
Visibility enabled and Unbookmarked
RESULTS - Unvisible in HUD, Searchable in Center and Unvisible in Webtop

Test 3-
Visibility disabled and Bookmarked
RESULTS -Visible in HUD, unsearchable in Center and Visible in Webtop

Test4-
Visibility disabled and unbookmarked
RESULTS - Unvisible in HUD, unsearchable in Center and Unvisible in Webtop.
