### ISSUE TITLE
IE9- Launching new tab and launching in webtop is not working as expected 

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-webtop#508]
Click on triple lines menu, select Settings under Personalized
In POP box activate "Open in WebTop" 
In HUD launch an application 
Expected Results: If listed on WebTop, display that dashboard with application  
                              If not listed on WebTop, display new dashboard with application
In POP activate "Open in New Tab
In HUD launch an application 
Expected Results: Opens a new tab displaying listing.

**Comment by clarkjefcoat** [comment]
I don't think this is particular to IE9.

If I create a new dashboard and then delete my original default dashboard, I find that "Open in Webtop" no longer works.  That is, if I go to webtop and the URL shown in the URL bar ends in anything other than "sticky-0/0" then neither the setting "Open in Webtop" nor the "Launch in webtop" dropdown from HUD work as expected.

**Comment by hoganmaps** [comment]
ie9 issues being moved out of IOB and in to backlog. need to evaluate later

**Comment by hoganmaps** [comment]
I don't believe this is an issue anymore.

steps (In IE9):
Go to webtop, create dashboard, delete default dashboard.
In hud, launch widget in to webtop
Widget loads in non default dashboard

**Comment by jal-vsi** [comment]
Passed Chris test in IE9 Master environment.  Also passes in IE11, FF24, and CH36 (Master environment).  NOTE: if you have multiple folders named the same (e.g., New Dashboard), app launches from HUD will open same in each dashboard.

**Comment by tonyalletag** [comment]
Our baseline is IE11. No longer an issue
