### ISSUE TITLE
"Open in Webtop" does not work after default dashboard has been deleted

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-webtop#509]
If I create a new dashboard and then delete my original default dashboard, I find that "Open in Webtop" no longer works. That is, if I go to webtop and the URL shown in the URL bar ends in anything other than "sticky-0/0" then neither the setting "Open in Webtop" nor the "Launch in webtop" dropdown from HUD work as expected.

I see this issue in Chrome and FF.  It appears to be a different issue than the IE9 issue noted in #508.

**Comment by mparizernc** [comment]
All Browsers

I created a new dashboard and removed the default dashboard. I then added a listing to the webtop in both methods listed in the bug and ran into no issue. Ready to be tested in Prod.
