### ISSUE TITLE
Submit a Listing - not able to access from HUD and WebTop

### ISSUE THREAD

**Issue by kgordon-1** [ozone-development/ozp-webtop#521]
In WebTop, select the triple lines, next select Submit a Listing.  Nothing happens.
In HUD, select the triple lines, next select Submit a Listing, this takes me to Center.  I wanted to create a listing.

In Center, this will take me to submit a listing. 

If a user is not suppose to access Submit a Listing from HUD or WebTop, then it should be grayed out or remove from the list.

**Comment by kgordon-1** [comment]
See also WebTop 423 they maybe related.

**Comment by mparizernc** [comment]
If HUD is not working that should because of a bad configuration I would think the Listing Management wouldn't work either in that case.

Webtop has not coded the link to use the configuration yet to my understanding.

**Comment by hoganmaps** [comment]
current route to submit a listing in center is `/dist/#/edit`

**Comment by hoganmaps** [comment]
@alan fixed this as part of ticket #423

**Comment by arw180** [comment]
verified

**Comment by kgordon-1** [comment]
Passed - tested in STG
Verified fixed: From HUD, WebTop and Center, able to access Submit Listing, save and approve for posting in center.  However, accessing Submit listing from HUD, Listing Type menu is blank (Refresh brings it back). This is already a ticket 266.
