### ISSUE TITLE
Add profile modal and link from ozp toolbar

### ISSUE THREAD

**Issue by arw180** [ozone-development/ozp-webtop#530]
The modal should have the same content as the corresponding modal in HUD. Clicking Profile in the ozp toolbar should invoke the modal.

**Comment by mparizernc** [comment]
All Browsers

Verified that the Profile window has been created and the rest of the clean up and hooking it up to the back end will be done as part of ticket #534. This is ready to be looked at in Prod with the exception of functionality yet to be completed.

**Comment by jloveland18** [comment]
tested in staging 0.4.5

All Browsers

Verified that the Profile window does appear.
