### ISSUE TITLE
Global Toolbar - Update Dev Resources to open in new tab

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-webtop#541]
Update the link to "Developer Resources" to open in a new tab to match Center and HUD

**Comment by sdeighan** [comment]
Pull Request in queue

**Comment by mparizernc** [comment]
All Browsers 

Verified that the Dev Resources link opens in a new tab.  Ready for Prod testing.

**Comment by kgordon-1** [comment]
Passed – Tested in STG
Verified fixed by clicking on Developers Resources (from HUD, Center and WebTop) and it open in a new tab.
