### ISSUE TITLE
App Toolbar Images too large need to be scaled

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-webtop#555]
When a huge image is added to a widget in the largeIcon fields, the image in the apptoolbar on webtop is not scaled, resulting in a huge, awkward cut off icon toolbar. Clark put together an example for airmail 2 on di23 develop to test with

**Comment by wski** [comment]
Tested with CoalaCola and image was scaled down automatically, Resolved.

**Comment by kgordon-1** [comment]
Had large size image loaded and added to an app in the testing environment.  Bookmark app and reviewed it in HUD and WebTop.    Bottom tool bar is displayed with all app’s icons that were selected to display in WebTop and the top toolbar displays usual icons.
