### ISSUE TITLE
508 compliance standards - Add "alt" tags to all webtop modals

### ISSUE THREAD

**Issue by SOAP1914** [ozone-development/ozp-webtop#560]
Make Webtop 508 compliance
* add alt tags

**Comment by sdeighan** [comment]
I would really suggest breaking this out into several different tickets. May I suggest changing the title to "508 - Add alt tags"? Otherwise, this ticket will be alive forever.

**Comment by SOAP1914** [comment]
@sdeighan I totally agree - Thanks :)

**Comment by hoganmaps** [comment]
we need a plan to implement this. Figuring out a plan as part of ticket #590
