### ISSUE TITLE
Bug - Apps Minimized in Desktop switch to Gridster and expand but have inactive icons

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-webtop#561]
1. Open a 'desktop' dashboard in Webtop with at least one application open.
2. Minimize application
3. Open "Dashboard" menu
4. Edit current dashboard
5. Change mode to "Grid"

If you look at the toolbar when the dashboard has reloaded, you will see that the minimized application's icon is "deactivated" but the application itself is active in the dashboard.

**Comment by arw180** [comment]
verified

**Comment by kgordon-1** [comment]
Passed (Tested on STG)
Follow instructions from ticket and observed apps located at bottom tool bar.  Clicked on tool bar icons to display apps on WebTop and remove apps from WebTop (not delete).
