### ISSUE TITLE
508 compliance standards - Add "alt" tags to all webtop toolbars

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-webtop#562]

**Comment by wski** [comment]
I was unable to find the alt tags when using Webtop in the toolbars

**Comment by clarkjefcoat** [comment]
For the app icon, can we add specific descriptions in the alt tag rather than just "Application Icon".

**Comment by hoganmaps** [comment]
we need a plan to implement this. Figuring out a plan as part of ticket #590
