### ISSUE TITLE
Desktop View - Applications stack directly when added as a group to the Webtop

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-webtop#567]
When applications are added at the same time to the Webtop, the chromes are generated on top of each other, as seen below.
### Current Display
![appsstacked](https://cloud.githubusercontent.com/assets/7987446/7733140/3f96dae6-fefb-11e4-9285-788b2e8a6872.png)

It would be easier for users to find and then organize their newly added applications if the windows were added in positions more like the "Cascade windows" function
### Proposed Display
![cascadedapps](https://cloud.githubusercontent.com/assets/7987446/7733172/7e68a8f8-fefb-11e4-91d7-47e18be25475.png)

**Comment by bhalt** [comment]
Also, can we add a gentle highlight to the new app (on both grid and desktop views): 

CSS on li.gridster-item for 1.5-2 seconds:


  box-shadow: 0 0 15px #009dd3;






![uploads/e9435110-bf06-4316-bd98-ebaa5471b290/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe9435110-bf06-4316-bd98-ebaa5471b290%2Fblob)

**Comment by hoganmaps** [comment]
I'll put this in another ticket when I get back

Chris Hogan
@hoganmaps

**Comment by hoganmaps** [comment]
So this fix exposes another bug we have with column limits in desktop view that was less noticeable before.

**Comment by mparizernc** [comment]
I have tested this on develop with all the browsers and verified opening widgets with new dashboards, existing dashboards and opening from the HUD.

The border work will be done in #596.

**Comment by mparizernc** [comment]
Verified on staging that in desktop that listings when opened are now cascaded over the last opened widget and are no longer stacked on top of each other.
