### ISSUE TITLE
Edit dashboard name/layout type does not always save

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-webtop#569]
When you edit the names of two dashboards and reload, only the second change is saved

**Comment by wski** [comment]
I was able to save it every time, resolved.

**Comment by kgordon-1** [comment]
Passed - tested in STG
Verified fix by changing the name of several dashboards and clicking save for each.  Changed name of dashboard while in it or displaying it.  Name was saved and changed displayed on tool bar.  Changed name and changed to desktop click saved.  Name was saved and changed displayed on tool bar and in dashboard.
