### ISSUE TITLE
Add explanatory message in Webtop "add apps" modal when users don't have bookmarked apps

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-webtop#572]
If users try to add an app to their Webtop but don't have any apps bookmarked -- display a message rather than empty modal. Same messsage content as HUD:

![uploads/6be0666f-ebd4-44f9-94bf-3face24acfb3/webtop_noapps.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6be0666f-ebd4-44f9-94bf-3face24acfb3%2Fwebtop_noapps.png)

**Comment by hoganmaps** [comment]
this will be in todays release
