### ISSUE TITLE
HUD - Fix bookmark tile menu behavior to close on background/outside click

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-webtop#573]
The HUD bookmark tile menus should have the same behavior as other standard menus. If the user clicks elsewhere on the screen, the menu should automatically close rather than keeping two menus open at once.

![uploads/6963ab3d-dc6b-4216-8a58-660fba1ca7ab/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6963ab3d-dc6b-4216-8a58-660fba1ca7ab%2Fblob)

**Comment by rpokorny** [comment]
This behaves the same way as the My Listings page in center.  I recall that, at least for the My Listings page, this was an intentional decision by @sdeighan .

**Comment by bhalt** [comment]
Just realized I put in the wrong HuBoard -- moving to OZP-HUD. I'll talk to @sdeighan
