### ISSUE TITLE
Streamline behavior of clicking an app icon in the webtop toolbar in grid views (highlight changes)

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-webtop#577]
Functionality of an toolbar app icon click in both grid/desktop should be simply bringing app to the top of the pile (desktop) / scroll to the app (grid) and highlight the app (li.gridster-item) for 1.5-2 seconds with this CSS:

  box-shadow: 0 0 15px #009dd3;

Preview of highlight CSS:

![uploads/e9435110-bf06-4316-bd98-ebaa5471b290/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe9435110-bf06-4316-bd98-ebaa5471b290%2Fblob)

**Comment by bhalt** [comment]
@SOAP1914 : as we discussed in the iteration meeting / slack. Let me know if you need anything else from me or want to discuss implementation further!

**Comment by bhalt** [comment]
Also, this removes the "minimizing/docking" ability in desktop, so remove the "minus" icon from the app chrome. Should we turn the "plus" icon in the app chrome to a full-screen icon? @sdeighan?

**Comment by SOAP1914** [comment]
remove the "minus" icon from the app chrome is issue 
#595

**Comment by mparizernc** [comment]
@SOAP1914 @bhalt 

So I started to test this ticket and I am a little confused but what the expected functionality is supposed to be.

On Grid View if I select the icon of a widget it highlights blue and make it active which I believe is correct.

On Desktop View

1. I thought if I selected the icon it was supposed to make the widget highlight blue and make it active as well but it minimizes the widget. Which should it be doing?

2. Both the maximize and minimize button appear at normal size. If I hit maximize it makes full screen and both buttons are still shown. If I hit the minimize button at normal size it makes it disappear but at full size it returns it to normal size.  Is this the expected behavior?

**Comment by bhalt** [comment]
1. Correct - it should highlight the widget blue and bring it to the front
2. The maximize and minimize buttons should be consolidated into one (same icon as the webtop fullscreen icon). That should appear as a fullscreen icon with outward arrows when at normal size, and should change to the inward arrows icon when maximized. All the icon materials needed are in the repo.

Sounds to me like nothing has been changed in the version you are testing. @SOAP1914 was the correct repo pushed?

**Comment by mparizernc** [comment]
Ok looking at it again looks #595 was created to do the icons but without them this functionality is a bit confusing.  Also @bhalt in desktop when clicking the icon on the bottom toolbar what should happen?

**Comment by bhalt** [comment]
It should be highlighted, and if it is underneath other apps, it should be brought to the front of the stack. We're removing all minimizing-to-the-dock functionality.

**Comment by mparizernc** [comment]
@bhalt Thanks.That is not working for this ticket so I am kicking it back for that to be fixed.

**Comment by SOAP1914** [comment]
I apologize for the confusing 
@bhalt @mparizernc I've broke this ticket up in 3 parts #596 #595 (this ticket) was just for the highlight.
#596 is to make Desktop act like Grid view (which is across a few files according to @hoganmaps )
so I'll change the title to this ticket to reflect (highlight) .

**Comment by SOAP1914** [comment]
ps I'll take away the active blue line under the apps too. (add it to another ticket (maybe #595)

**Comment by mparizernc** [comment]
@SOAP1914 OK so what exactly is done in this ticket that needs to be tested.  I see the blue outline was added to Grid View but has anything been done for Desktop View for this ticket?

**Comment by SOAP1914** [comment]
@mparizernc only the blue outline and screen moves to app being click in Grid view

**Comment by mparizernc** [comment]
Moving this back to resolved as the previous comment was done.

**Comment by mparizernc** [comment]
Verified in develop that on the Grid View that selecting the icons in the bottom tool bar highlights the widget in blue and brings focus to it.

**Comment by mparizernc** [comment]
Verified on Staging that on the Grid View selecting the icons on the bottom toolbar, highlight the widget and bring focus to it by scrolling to the selected widget.
