### ISSUE TITLE
Global Toolbar - Disable Notifications when there are no notifications

### ISSUE THREAD

**Issue by sdeighan** [ozone-development/ozp-webtop#582]
When there are no notifications, the notifications menu/button should be disabled. On click, the styling should not change.

**Comment by jal-vsi** [comment]
Tested/Verified pass on all 4 browsers (IE9, IE11, FF24, CH36) logged in as User to confirm there is no styling changes when notification area is clicked.  Same results logged in as Admin.

**Comment by mparizernc** [comment]
Tested on IE10, FF and Chrome and verified that there is no style changes when clicking on the notification icon and there are no notifications.
