### ISSUE TITLE
Add tooltips to nav/controls in Webtop and the Global Toolbar

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-webtop#583]
Ask @bhalt with any further questions regarding implementation. Tooltips should be on a (half second?) delay. Exact implementation also needed in HUD (# 94) and Center (# 283).
<br><br>

![uploads/0fcaca7e-bdff-4c10-9334-288e151e2e1c/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0fcaca7e-bdff-4c10-9334-288e151e2e1c%2Fblob)

<br><br>
1) GLOBAL TOOLBAR - HUD: "<b>HUD</b>"<br>
2) GLOBAL TOOLBAR - CENTER: "<b>Center</b>" (config file tokenization for highside) <br>
3) GLOBAL TOOLBAR - WEBTOP: "<b>Webtop</b>"<br>
4) GLOBAL TOOLBAR - NOTIFICATION: "<b>No new notifications</b>" or "<b>1 new notification</b>" or "<b>__ new notification<u>s</u></b>"<br>
5) GLOBAL TOOLBAR - HELP: "<b>Help</b>"<br>
6) GLOBAL TOOLBAR - MENU: "<b>Menu</b>"<br>
7) WEBTOP BLUE + BUTTON: "<b>Add apps</b>"

**Comment by bhalt** [comment]
@hoganmaps

**Comment by mparizernc** [comment]
@hoganmaps I can say this is directly related to the tool tip but when you add a Notification the icon performs a great magic trick and disappears from the tool bar.
