### ISSUE TITLE
Remove the "minus" icon from the app chrome/ Remove the "active" status (blue borders)

### ISSUE THREAD

**Issue by SOAP1914** [ozone-development/ozp-webtop#595]
remove the "minus" icon from the app chrome. The "plus" icon should now be a "maximize" icon when normal size, and switch to a "minimize" icon when fullscreen.

and

Remove the "active" status (blue borders / opacity change) in both grid/desktop toolbar app icons

**Comment by jal-vsi** [comment]
The 'minus' icon is gone, the 'plus' icon replaced with 'min/max' icon, so it works fine.  The 'Blue Borders' are gone but there is no active select from the icons in the tray as it had before.
