### ISSUE TITLE
Delete dashboard should have a modal popup rather than a browser alert.

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-webtop#599]
Currently this:
<br><br>
![uploads/4b9e1700-af30-4456-b872-f69473213937/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4b9e1700-af30-4456-b872-f69473213937%2Fblob)
<br><br>
Should be this:
<br><br>

![uploads/80454a88-e568-4c52-80e8-ed6ce44e5bb6/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F80454a88-e568-4c52-80e8-ed6ce44e5bb6%2Fblob)

**Comment by jal-vsi** [comment]
Verified this is working (testUser1) on all browsers (IE9, IE11, FF24, CH36)

**Comment by mparizernc** [comment]
Accidentally Closed

**Comment by mparizernc** [comment]
Verified in the staging environment in all of the available browsers.
