### ISSUE TITLE
column issue in desktop view

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-webtop#603]
When you move widgets around and add new widgets in, a column limit prevents new widgets from being added. We need to figure out what is going on with this - do we need to limit the number of widgets that can be on a dashboard, or limit where on a dashboard widgets can go

![uploads/8ceadc51-33aa-42df-aab5-ee0edd62bee4/Screen Shot 2015-06-30 at 5.51.13 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8ceadc51-33aa-42df-aab5-ee0edd62bee4%2FScreen+Shot+2015-06-30+at+5.51.13+PM.png)

**Comment by mparizernc** [comment]
I am unable to reproduce the error in develop.

**Comment by mparizernc** [comment]
The problem was no longer seen on Staging verified by adding the max number of widgets (15).
