### ISSUE TITLE
Deleting a dashboard does not refresh the page and default back to the previous dashboard

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-webtop#605]
I had two dashboards and deleted one after being prompted and hitting OK I was still on the dashboard I deleted. I had to select the other dashboard for it to be removed. (If I refresh the dashboard disappears but I then I am not on any dashboard.) I should move to the previous dashboard once I delete one.

**Comment by hoganmaps** [comment]
I believe that this issue was related to upgrading to angular 1.4, and has since been resolved. Tested in latest chrome and ie9

**Comment by jal-vsi** [comment]
Passed test in Master using the 4 browsers.  User: 1) creates new dashboard (tested in both views), 2) blank dashboard or starts some apps, 3) deletes folder, then 4) returns to default dashboard.

**Comment by mparizernc** [comment]
Verified that when deleting a dashboard the browser refreshes and takes the user to the Default Dashboard. Verified on Staging on IE10, FF and Chrome.
