### ISSUE TITLE
Create an alert message for when a user tries to add more apps that the dashboardMaxWidgets

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-webtop#607]

**Comment by jal-vsi** [comment]
Passed test in Master using 4 browsers (User, Org Steward, Admin).  If you exceed the app limit (15) you receive a pop-up message "You've reached your dashboard app limit" indicating you need a new dashboard to use more.  If you open 16 into a blank dashboard the first 15 open and you get the error message (IE11 doesn't allow you to OK that and continue, it freezes the browser).

**Comment by clarkjefcoat** [comment]
Tested in staging (IE9, FF24, Chrome36)
