### ISSUE TITLE
Global Toolbar - Add Helpdesk Link to Dropdown Menu

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-webtop#613]

**Comment by jal-vsi** [comment]
Testing in Master environment (Iteration 29) using testUser1 role passes in IE9, IE11, and FF24 but fails in CH36:
Accessing "Contact Help Desk" from drop down in HUD, Center, Webtop:  causes email access to help desk in IE9, IE11, FF24, but not CH36 (no response).

**Comment by mparizernc** [comment]
Verified in all of the browsers in Staging that the link goes to the Helpdesk site.  I also spot checked other links on the user drop down and found no issues.
