### ISSUE TITLE
The invalid link "Center Settings" should not be displayed to users who cannot access it

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-webtop#618]
User and Org Steward have invalid links to "Center Settings" in the Webtop drop-down.  These links/choices need to be removed.

**Comment by jal-vsi** [comment]
Passed test (eliminate "Center Settings" in Webtop) in Master for both User and Org Steward.

**Comment by mparizernc** [comment]
Verified that Center Settings appears AML Stewards and not for Org Steward and users on Staging. Verified with IE10, FF and Chrome.
