### ISSUE TITLE
Org Steward should see "Metrics" link in drop-down menu

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-webtop#619]
The Org Steward does not have a link to "Metrics" in the drop-down menu.  This link is in HUD and Center.  The link needs to be added to Webtop.

**Comment by jal-vsi** [comment]
Passed test (Org Steward now has link to Metrics from Webtop) in Webtop's drop-down menu.

**Comment by mparizernc** [comment]
Verified that metrics appears for Org Steward and AML Stewards and not for user on Staging. Verified with IE10, FF and Chrome.
