### ISSUE TITLE
App Listing in Bookmark Modals are not correctly alphabetized

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/ozp-webtop#620]
It looks like the app listing are case sensitive when being alphabetized.  So MoonMap would be listed ahead of iMap or ePhone. 

Listing order should not be case sensitive

**Comment by jal-vsi** [comment]
Passed test by creating 4 apps in Master (a1PPS, aPPS, bPPS, cPPS, dPPS).  All alphabetized as expected in Most Popular.

**Comment by clarkjefcoat** [comment]
Tested in staging
