### ISSUE TITLE
Apps not opening in Webtop using IE9 or IE11

### ISSUE THREAD

**Issue by jal-vsi** [ozone-development/ozp-webtop#625]
After changing the Center Menu Personalize Settings to "Open in Webtop", the apps  launched from HUD do not open in Webtop.  Using FF24 and CH36, they do open in Webtop as expected

**Comment by hoganmaps** [comment]
This ended up being a problem we just addressed in ozp-react-commons, check out develop to see if this is still an issue?

**Comment by jal-vsi** [comment]
Passed test in both IE browsers (in CI-Develop) with User, Org Steward, and Admin.  Changed center settings to "launch into Webtop".  Multiple launches with each user works fine.
