### ISSUE TITLE
When library reloaded on launchFolder, push bookmarked apps in to available apps

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-webtop#631]
When new apps are bookmarked and the user launches a folder, currently, the page has to be reloaded for the widgets to display in the add Widgets modal

**Comment by jal-vsi** [comment]
IE9 fails to create a new dashboard, instead when you launch a folder you are taken to the default dashboard (i.e., new dashboard is not created).
IE11, FF, and CH pass testing in Develop launching/creating new dashboards with 2 or 3 apps.
NOTE: the dashboard create allows for multiple dashboard titles (e.g., New dashboard, Dashboard XX (xx being a random number), New Dashboard 1).  Customer should pick one style when creating from HUD or Webtop.

**Comment by jal-vsi** [comment]
Same test results in Master (IE9 failure)

**Comment by jal-vsi** [comment]
IE9 not supported, this issue passes testing per IE11, FF, and CH

**Comment by tonyalletag** [comment]
Baseline is IE11
