### ISSUE TITLE
Change Webtop to pull in the latest CSS file from ozp-bootstrap rather than a specific hard-coded version

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-webtop#632]
See hardcoded line here: https://github.com/ozone-development/ozp-webtop/blob/c3bc1d1b8a0edc5bda8f30a35fba185592053951/bower.json#L19

**Comment by jal-vsi** [comment]
Chris said for testing: "I don't think there is, other than looking at the github repo and just seeing the repo name change"
