### ISSUE TITLE
sideload new app data when widget is shared to webtop

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-webtop#633]
When a user launches a folder from hud or from a URL, bookmarked widgets should show up in the add applications modal.

**Comment by jal-vsi** [comment]
Working with Chris on some problems in test (e.g., folder launch not working (IE, FF, CH)).

**Comment by clarkjefcoat** [comment]
If you already have the maximum number of dashboards created then you will not be able to open a shared link.  If this is the problem you are seeing, it has been documented as #642.

**Comment by jal-vsi** [comment]
#631 passed testing in IE11, FF, and CH (IE9 not supported) so this one is complete due to being the same as #631
