### ISSUE TITLE
Contact Modal

### ISSUE THREAD

**Issue by KageRyu7** [ozone-development/ozp-webtop#635]
A contact modal that will contain links to help, feature requests, feedback, and social media. This is a solution to the original issue here...
https://github.com/ozone-development/ozp-center/issues/348

This will also be in...
ozp-react-commons
https://github.com/ozone-development/ozp-react-commons/issues/26
Hud
https://github.com/ozone-development/ozp-hud/issues/126

**Comment by mparizernc** [comment]
I have tested this locally in IE9,11, Firefox and Chrome and found no issues. Ready for testing on master.

**Comment by jal-vsi** [comment]
Portions failed in Master (IE9/11, FF, CH).  Passed: email links for Contact Help Desk and Give Feedback.  Failed: 1) Link for "Help Center" opens a new instance of Webtop. 2) "Submit a Request" does not have a link to the email service. 3) "Chirp, Pin, Chat, and Blog" all don't have active links.

**Comment by hoganmaps** [comment]
we need to add #2 and #3 to the ozone config (or point them at existing config items) and send a second pr

**Comment by hoganmaps** [comment]
actually we should put that in another ticket, I will open it and move it to ready.

**Comment by clarkjefcoat** [comment]
In our staging and production environments we have these set in OzoneConfig.js to reasonable values.  To resolve this ticket we should do the same for dev.

**Comment by tdressel** [comment]
Tested on IE11, Chrome46 and FF36

HUD and Center
"Help Center" open a PlacerholderUserGuide.pdf.
Contact Helpdesk opens compose email.
Give Feedback opens compose email.
Submit a Request opens a compose email.
Connect with us - Chirp, Pin, Chat and Blog each open a new tab.

WebTop
"Help Center" opens a second webtop tab
Contact Helpdesk opens compose email.
Give Feedback opens compose email.
Submit a Request does nothing
Connect with us - Chirp, Pin, Chat and Blog does nothing.

**Comment by tdressel** [comment]
WebTop Help tested again on latest using IE10, Chrome46 and FF36
"Help Center" opens a Help modal
Contact Helpdesk opens compose email form - helpdesk@address.com
Give Feedback opens compose email form - person@address.com
Submit a Request opens a compose email form - request@address.com
Connect with us - Chirp, Pin, Chat and Blog each opens a blank tab.

**Comment by tdressel** [comment]
Tested on Chrome, FF and IE.
